# Generated by Django 5.0 on 2024-01-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='id_carta',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
